platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!


target 'FG_OneKeyLoginSDK' do
  

  # self frameworks
  pod 'CL_ShanYanSDK'
  


end

# 兼容Xcode14.3
post_install do |installer|
  

  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
       end
    end
  end
end
